name: "Proxy test"
description: "Tests using a proxy specified by the https_proxy environment variable"
versions: ["linked", "nightly-latest"]
operatingSystems: ["ubuntu"]
container:
  image: ubuntu:22.04
  options: --dns 127.0.0.1
  run: |
    apt-get update
    apt-get install -y gh
services:
  squid-proxy:
    image: ubuntu/squid:latest
    ports:
      - 3128:3128
env:
  https_proxy: http://squid-proxy:3128
steps:
  - uses: ./../action/init
    with:
      languages: javascript
      tools: ${{ steps.prepare-test.outputs.tools-url }}
  - uses: ./../action/analyze
